add_song(music_collection, "Сподіваюсь, з тобою все гаразд", ["mistmorn"], ["post-punk"])
add_song(music_collection, "Небо", ["SadSvit"], ["post-punk"])
add_song(music_collection, "Танці", ["SadSvit", "Sad Novelist"], ["post-punk"])
add_song(music_collection, "сам собі наказ", ["хейтспіч", "Sad Novelist"], ["post-punk", "punk-rock"])
add_song(music_collection, "хвора на любов", ["vioria"], ["kitty-rock"])
add_song(music_collection, "То моє море", ["ВІКА"], ["synthpop"])
add_song(music_collection, "Black Catcher", ["VK Blanka"], ["pop"])
add_song(music_collection, "Мовчати", ["Ірина Білик", "Скрябін"], ["pop"])
add_song(music_collection, "Реквієм", ["postluv", "Sad Novelist", "Відчай"], ["pop"])
add_song(music_collection, "Десять причин", ["OTOY"], ["rap"])
add_song(music_collection, "Загублене літо", ["Electrobirds"], ["post-punk"])
add_song(music_collection, "Файна", ["Міша Правильний"], ["rap"])
add_song(music_collection, "Де Твоя Лінія", ["Лінія Маннергейма"], ["rock"])
add_song(music_collection, "30", ["DK Energetyk"], ["post-punk"])
add_song(music_collection, "Байдужий", ["Luna Rozza", "BaWN"], ["post-punk"])
add_song(music_collection, "Пластик", ["паліндром"], ["alt-rock", "post-punk"])
add_song(music_collection, "Тління", ["Sad Novelist"], [])

delete_song(music_collection, "Black Catcher")

edit_song(music_collection, "Тління", new_artists: ["Sad Novelist", "SadSvit"], new_genres: ["post-punk"])
